config-version: 26

# Should we collect anonymous data about your server?
# false by default.
bstats: false

# Should we remove [Not Secure] from /say?
# There is a very small chance of catching something
# that should not be caught. If that happens report the
# incident to Github issues of AntiPopup.
filter-not-secure: true

# Should we prevent messages from being reported?
# Leave as true unless you have a different plugin stripping those.
strip-signature: true

# We dont need that packet if
# we dont sign messages.
dont-send-header: true

# Should setup be ran on first start?
# Useful for all kinds of setups or server hosts.
auto-setup: false

# NMS - Only for 1.19.3
# PACKET - Only up to 1.19.2
# BUKKIT - Version independent, less compatible, has URLs in messages
mode: PACKET

# Do not touch ones below!
first-run: true
ask-bstats: true
setup-mode: true